name = "poker-analyzer"
compatibility_date = "2024-03-10"
pages_build_output_dir = "."

[[d1_databases]]
binding = "ACCESS_DB"
database_name = "poker-access"
database_id = "67858159-6c10-4abf-9750-ef8be65650c3"
